# -*- coding: utf-8 -*-
"""Copie de sally-projet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ENqljYOseAIIgMtAhdRN6mPke7bAXwQi
"""

import streamlit as st

# Define custom styles using HTML and CSS
custom_styles = """
    <style>
        body {
            font-family: 'Arial', sans-serif;
            color: #008080;  /* Change the color value to your desired color */
        }
        .italic {
            font-style: italic;
            color: #800080;  /* Change the color value to your desired color */
        }
        .bold {
            font-weight: bold;
            color: #000080;  /* Change the color value to your desired color */
        }
    </style>
"""

# Apply custom styles
st.markdown(custom_styles, unsafe_allow_html=True)

# Example text with different styles and colors
st.markdown("This is normal text.")
st.markdown("<p class='italic'>This is italic text.</p>", unsafe_allow_html=True)
st.markdown("<p class='bold'>This is bold text.</p>", unsafe_allow_html=True)

