# -*- coding: utf-8 -*-
"""Copie de  Streamlit : build and share data apps1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15M0E4c87-Z1XBBd1RExrrk1Hr0Dll6J0
"""

pip install streamlit

import pandas as pd
url = "https://raw.githubusercontent.com/murpi/wilddata/master/quests/cars.csv"
df = pd.read_csv(url)

df

df.info()

import streamlit as st
import pandas as pd
cont = st.sidebar.radio("Continent of analysis", df["continent"].unique())
filtered_df = df[df["continent"] == cont]

import seaborn as sns
import matplotlib.pyplot as plt
filtered_df_corr = filtered_df.corr()
sns.heatmap(filtered_df_corr, cmap = 'vlag', center = 0)

numeric_columns = filtered_df.select_dtypes(include=['float64', 'int64'])

# Histogrammes
numeric_columns.hist(bins=20, figsize=(15, 10))
plt.suptitle("Distribution des variables numériques", y=1.02)

# Boxplots
plt.figure(figsize=(15, 10))
sns.boxplot(data=numeric_columns, palette="Set2")
plt.title("Boxplots des variables numériques")

#pip show numpy

#pip show seaborn

#pip show pandas

#pip show streamlit

# https://github.com/sally995/streamlitSally/upload bi hayda el link cz ma chtaghalet local 3al laptop chtaghalet 3a site so,
#be3mel new reposetry bi gethub w bsami , be3mel downlowd la hayde el colab(save .py bel akhir) wel notepad(fi versions li mahtoutin hn), lezem ykoun esmou requirements elnotepad
#bas e3meloun dowload bel github brouh 3a streamlit https://share.streamlit.io/ w bhet esem reposetry li ftahta w abel ekher chi bhet nafes esem el collab li hetaytou bi gethub
#w hek bkoun 3melet el streamlit

