# -*- coding: utf-8 -*-
"""sally-projet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15M0E4c87-Z1XBBd1RExrrk1Hr0Dll6J0
"""

import pandas as pd
url = "https://raw.githubusercontent.com/murpi/wilddata/master/quests/cars.csv"
df = pd.read_csv(url)

import streamlit as st
import pandas as pd
cont = st.sidebar.radio("Continent of analysis", df["continent"].unique())
filtered_df = df[df["continent"] == cont]

import seaborn as sns
import matplotlib.pyplot as plt
filtered_df_corr = filtered_df.corr()
sns.heatmap(filtered_df_corr, cmap='vlag', center=0, annot=True)
st.pyplot(plt)

numeric_columns = filtered_df.select_dtypes(include=['float64', 'int64'])

# Histogrammes
numeric_columns.hist(bins=20, figsize=(15, 10))
plt.suptitle("Distribution des variables numériques", y=1.02)
st.pyplot(plt)

# Boxplots
st.figure(figsize=(15, 10))
sns.boxplot(data=numeric_columns, palette="Set2")
st.title("Boxplots des variables numériques")
st.pyplot()

# Set font to 'Wright', make text italic, and bold
st.markdown(
    """
    <style>
        body {
            font-family: 'Wright', sans-serif;
        }
        .italic {
            font-style: italic;
        }
        .bold {
            font-weight: bold;
        }
    </style>
    """
    , unsafe_allow_html=True
)

# Example text with different styles
st.markdown("This is normal text.")
st.markdown("<p class='italic'>This is italic text.</p>", unsafe_allow_html=True)
st.markdown("<p class='bold'>This is bold text.</p>", unsafe_allow_html=True)

#https://sally-projet-kqjvyaszfhxzgfrjxvjgs5.streamlit.app/